f=open("f1.txt","w")
a=f.write("hi")
print(a)
# print("File Name:",f.name)
# print('File Mode:',f.mode)
# print("File Readable:",f.readable())
# print('File Writable:',f.writable())
# print("File Closed:",f.closed)
f.close()